//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_platformer : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Vector2 Move
        {
            get
            {
                return SteamVR_Actions.platformer_Move;
            }
        }
        
        public virtual SteamVR_Action_Boolean Jump
        {
            get
            {
                return SteamVR_Actions.platformer_Jump;
            }
        }
        
        public virtual SteamVR_Action_Boolean VR_Brush_Btn
        {
            get
            {
                return SteamVR_Actions.platformer_VR_Brush_Btn;
            }
        }
        
        public virtual SteamVR_Action_Vector2 MoveAround
        {
            get
            {
                return SteamVR_Actions.platformer_MoveAround;
            }
        }
        
        public virtual SteamVR_Action_Vector2 Move_Y_Axis
        {
            get
            {
                return SteamVR_Actions.platformer_Move_Y_Axis;
            }
        }
        
        public virtual SteamVR_Action_Boolean ToggleFlying
        {
            get
            {
                return SteamVR_Actions.platformer_ToggleFlying;
            }
        }
        
        public virtual SteamVR_Action_Boolean IncreaseFlyingSpd
        {
            get
            {
                return SteamVR_Actions.platformer_IncreaseFlyingSpd;
            }
        }
        
        public virtual SteamVR_Action_Boolean DecreaseFlyingSPd
        {
            get
            {
                return SteamVR_Actions.platformer_DecreaseFlyingSPd;
            }
        }
        
        public virtual SteamVR_Action_Boolean M_Forward
        {
            get
            {
                return SteamVR_Actions.platformer_M_Forward;
            }
        }
        
        public virtual SteamVR_Action_Boolean M_Left
        {
            get
            {
                return SteamVR_Actions.platformer_M_Left;
            }
        }
        
        public virtual SteamVR_Action_Boolean M_Right
        {
            get
            {
                return SteamVR_Actions.platformer_M_Right;
            }
        }
        
        public virtual SteamVR_Action_Boolean M_Backward
        {
            get
            {
                return SteamVR_Actions.platformer_M_Backward;
            }
        }
        
        public virtual SteamVR_Action_Boolean BigJump
        {
            get
            {
                return SteamVR_Actions.platformer_BigJump;
            }
        }
        
        public virtual SteamVR_Action_Boolean InverseBigJump
        {
            get
            {
                return SteamVR_Actions.platformer_InverseBigJump;
            }
        }
        
        public virtual SteamVR_Action_Boolean Toggle_ActionSet
        {
            get
            {
                return SteamVR_Actions.platformer_Toggle_ActionSet;
            }
        }
        
        public virtual SteamVR_Action_Vector2 TwoAxis
        {
            get
            {
                return SteamVR_Actions.platformer_TwoAxis;
            }
        }
    }
}
