//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_default : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Boolean InteractUI
        {
            get
            {
                return SteamVR_Actions.default_InteractUI;
            }
        }
        
        public virtual SteamVR_Action_Boolean Teleport
        {
            get
            {
                return SteamVR_Actions.default_Teleport;
            }
        }
        
        public virtual SteamVR_Action_Boolean GrabPinch
        {
            get
            {
                return SteamVR_Actions.default_GrabPinch;
            }
        }
        
        public virtual SteamVR_Action_Boolean GrabGrip
        {
            get
            {
                return SteamVR_Actions.default_GrabGrip;
            }
        }
        
        public virtual SteamVR_Action_Pose Pose
        {
            get
            {
                return SteamVR_Actions.default_Pose;
            }
        }
        
        public virtual SteamVR_Action_Skeleton SkeletonLeftHand
        {
            get
            {
                return SteamVR_Actions.default_SkeletonLeftHand;
            }
        }
        
        public virtual SteamVR_Action_Skeleton SkeletonRightHand
        {
            get
            {
                return SteamVR_Actions.default_SkeletonRightHand;
            }
        }
        
        public virtual SteamVR_Action_Single Squeeze
        {
            get
            {
                return SteamVR_Actions.default_Squeeze;
            }
        }
        
        public virtual SteamVR_Action_Boolean HeadsetOnHead
        {
            get
            {
                return SteamVR_Actions.default_HeadsetOnHead;
            }
        }
        
        public virtual SteamVR_Action_Boolean SnapTurnLeft
        {
            get
            {
                return SteamVR_Actions.default_SnapTurnLeft;
            }
        }
        
        public virtual SteamVR_Action_Boolean SnapTurnRight
        {
            get
            {
                return SteamVR_Actions.default_SnapTurnRight;
            }
        }
        
        public virtual SteamVR_Action_Single Trigger
        {
            get
            {
                return SteamVR_Actions.default_Trigger;
            }
        }
        
        public virtual SteamVR_Action_Single Grip
        {
            get
            {
                return SteamVR_Actions.default_Grip;
            }
        }
        
        public virtual SteamVR_Action_Vector2 ThumbstickPosition
        {
            get
            {
                return SteamVR_Actions.default_ThumbstickPosition;
            }
        }
        
        public virtual SteamVR_Action_Boolean Action1
        {
            get
            {
                return SteamVR_Actions.default_Action1;
            }
        }
        
        public virtual SteamVR_Action_Boolean Action2
        {
            get
            {
                return SteamVR_Actions.default_Action2;
            }
        }
        
        public virtual SteamVR_Action_Boolean ThumbstickButton
        {
            get
            {
                return SteamVR_Actions.default_ThumbstickButton;
            }
        }
        
        public virtual SteamVR_Action_Boolean MenuButton
        {
            get
            {
                return SteamVR_Actions.default_MenuButton;
            }
        }
        
        public virtual SteamVR_Action_Boolean ScaleUp
        {
            get
            {
                return SteamVR_Actions.default_ScaleUp;
            }
        }
        
        public virtual SteamVR_Action_Boolean ScaleDown
        {
            get
            {
                return SteamVR_Actions.default_ScaleDown;
            }
        }
        
        public virtual SteamVR_Action_Boolean UndoButton
        {
            get
            {
                return SteamVR_Actions.default_UndoButton;
            }
        }
        
        public virtual SteamVR_Action_Boolean RedoButton
        {
            get
            {
                return SteamVR_Actions.default_RedoButton;
            }
        }
        
        public virtual SteamVR_Action_Boolean SwitchMenu
        {
            get
            {
                return SteamVR_Actions.default_SwitchMenu;
            }
        }
        
        public virtual SteamVR_Action_Vector2 UltimateRadialMenuHover
        {
            get
            {
                return SteamVR_Actions.default_UltimateRadialMenuHover;
            }
        }
        
        public virtual SteamVR_Action_Boolean UltimateRadialMenuSelect
        {
            get
            {
                return SteamVR_Actions.default_UltimateRadialMenuSelect;
            }
        }
        
        public virtual SteamVR_Action_Vibration Haptic
        {
            get
            {
                return SteamVR_Actions.default_Haptic;
            }
        }
    }
}
